/**
 * Writes docs/playstore-listing.md — every Play Console field, ready to paste —
 * and fails if any text is over its character limit.
 *
 *   node tools/makeStoreListing.mjs
 *
 * Edit the texts here, not in the generated file.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const FRONT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const WEB = "https://saas-bharat-rail-go-web.vercel.app";
const EMAIL = "bharatrailgo@gmail.com";

const name = "BharatRailGo: Parcel Booking";
const short = "Railway parcel booking, bilti, GST bills and collections for booking agents.";
const full = `BharatRailGo is booking, bilti and billing software for railway parcel and station-to-station booking agents.

See every parcel, every train and every rupee on one live departure board — from the office computer or from your phone in the godown.

BOOKING
• Book a parcel in one line: type "NDLS 3pkg 60kg Ramesh topay 1550" and the form fills itself
• Rate card works out freight, hamali and other charges for each station
• Railway booking, own bogie, agent handover and delivery bookings
• RR number, train and bogie on every booking
• Daily summary and today's loading list

BILTI (POD)
• Make a bilti in your own number series
• Print it or share it on WhatsApp in one tap, with your logo and GSTIN
• Track delivery: received, loaded, in transit, unloaded, delivered or returned

PARTIES AND COLLECTIONS
• A running ledger for every party
• Record cash, UPI, bank or cheque payments — adjusted against the oldest dues first
• Outstanding report with ageing
• Send a payment reminder on WhatsApp with the amount due

GST INVOICES
• Bill a party for the month's bookings
• Railway freight you paid on the party's behalf is kept out of tax (pure agent)
• CGST + SGST or IGST worked out for you
• Print the tax invoice as a PDF

REPORTS
• Daily bookings, outstanding, station-wise and monthly GST
• Export any report to Excel

YOUR TEAM AND BRANCHES
• Owner, manager and staff logins — each sees only what they should
• Several branches in one account; staff see only their own branch
• Activity log: who created, changed, deleted or exported what, and when

YOUR DATA
• Nightly backups
• Download all your data whenever you want
• Your logo and colour on every bilti and bill
• Light and dark mode

BharatRailGo also runs in any browser and on Windows, so the counter, the godown and the owner's phone all see the same numbers.

BharatRailGo is an independent product for booking agents. It is not affiliated with Indian Railways and does not book railway tickets.

Questions or help: ${EMAIL}`;
const notes = `First release of BharatRailGo.

• One-line parcel booking with a rate card
• Bilti with delivery tracking, print and WhatsApp
• Party ledgers, payments and outstanding
• Pure-agent GST invoices
• Daily, outstanding, station and GST reports
• Branches, team roles and an activity log`;

const within = (label, text, max) => {
  if (text.length > max) throw new Error(`${label} is ${text.length} characters; the limit is ${max}`);
  return text.length;
};
const n1 = within("App name", name, 30);
const n2 = within("Short description", short, 80);
const n3 = within("Full description", full, 4000);
const n4 = within("Release notes", notes, 500);
const code = (t) => "```\n" + t + "\n```";

const md = `# BharatRailGo — Play Console copy-paste pack

Generated by \`tools/makeStoreListing.mjs\` — edit the texts there, not here.

Every field the Play Console asks for, in the order you meet them. Every value is inside its character limit (the script fails otherwise).

The listing only promises what the app does today. Play rejects listings that promise missing features.

---

## 0. Confirm these first

| Field | Value used here | Check |
|---|---|---|
| Developer name | BharatRailGo | must match your Play developer account |
| Public support email | \`${EMAIL}\` | must be an inbox someone reads |
| Privacy policy URL | \`${WEB}/privacy-policy.html\` | must open the policy text |
| Data deletion URL | \`${WEB}/delete-account.html\` | must open the deletion steps |
| Package name | \`com.bharatrailgo.app\` | create the Play app with THIS package; it can never be changed |
| Reviewer login | \`<REVIEWER_EMAIL>\` / \`<REVIEWER_PASSWORD>\` | see §5; never commit the real values |

---

## 1. Create app

| Field | Paste |
|---|---|
| App name (max 30) | \`${name}\` |
| Default language | \`English (India) – en-IN\` |
| App or game | App |
| Free or paid | Free |

---

## 2. Store listing → App details

**App name** (max 30 — this is ${n1})

${code(name)}

**Short description** (max 80 — this is ${n2})

${code(short)}

**Full description** (max 4000 — this is ${n3})

${code(full)}

**Graphics** — all in \`store-assets/\`

| Slot | File | Size |
|---|---|---|
| App icon | \`play-icon-512.png\` | 512 × 512 |
| Feature graphic | \`feature-graphic-1024x500.png\` | 1024 × 500 |
| Phone screenshots | \`screenshots/01…08\` | 1080 × 1920 |
| 7-inch tablet | \`screenshots-tablet7/01…08\` | 1200 × 1920 |
| 10-inch tablet | \`screenshots-tablet10/01…08\` | 1600 × 2560 |

Upload the screenshots in number order. The first two carry the pitch: most people see only those in search results.

---

## 3. Store settings

| Field | Value |
|---|---|
| App category | Business |
| Tags | Business tools, Finance & accounting |
| Email address | \`${EMAIL}\` |
| Website | \`${WEB}\` |

---

## 4. Policy → App content

### Privacy policy

${code(`${WEB}/privacy-policy.html`)}

### Ads

**No**, the app contains no ads.

### App access

Choose **"All or some functionality is restricted"** and add one instruction set:

| Field | Paste |
|---|---|
| Name | \`Full app access\` |
| Username | \`<REVIEWER_EMAIL>\` |
| Password | \`<REVIEWER_PASSWORD>\` |
| Any other instructions | the text below |

${code(`BharatRailGo is business software for railway parcel booking agents, so everything is behind a login.

Sign in with the credentials above to reach the full app: departure board, bookings, bilti, parties and ledger, payments, GST invoices, reports and settings. The account is a demo agency loaded with sample data. It holds no real customer or business data.

To try one-line booking: Bookings > New booking, type "NDLS 3pkg 60kg Ramesh topay 1550" in Quick entry and press Fill form.`)}

A login that does not work is the most common reason a login-only app is rejected. Test it in a private browser window before you submit.

### Content rating

Answer the questionnaire: every category is **No** (no violence, sexual content, profanity, drugs, gambling, user-to-user chat or location sharing). Expected result: **Everyone / PEGI 3**.

### Target audience

| Field | Value |
|---|---|
| Target age groups | **18 and over only** |
| Appeal to children | No |

### Data safety

- Does the app collect or share any required user data types? → **Yes**
- Is all user data encrypted in transit? → **Yes**
- Can users request that their data is deleted? → **Yes**

Deletion URL:

${code(`${WEB}/delete-account.html`)}

Declare these. For every one: **Collected = Yes, Shared = No**, not processed ephemerally, purpose **App functionality** (plus **Account management** where noted).

| Category | Type | Purpose | Note |
|---|---|---|---|
| Personal info | Name | App functionality, Account management | |
| Personal info | Email address | App functionality, Account management | |
| Personal info | Phone number | App functionality, Account management | |
| Personal info | Address | App functionality | office address; customers' addresses on bilti |
| Personal info | User IDs | App functionality, Account management | |
| Personal info | Other info | App functionality | GSTIN and PAN of the agency and its parties |
| Financial info | Purchase history | App functionality | bookings, bills and payments recorded by the agency |
| Photos and videos | Photos | App functionality | the agency's logo only — mark **Optional** |
| App activity | Other actions | App functionality | the activity log of staff actions |

The app does not collect location, contacts, messages, audio, health data or advertising IDs.

### Government, financial and health questions

| Question | Answer |
|---|---|
| Is this a government app? | **No** — it is independent and not affiliated with Indian Railways. The description says so. |
| Does it provide financial features? | **No** — it records bills and payments; it does not move money, lend or trade. |
| Is it a health app? | No |

---

## 5. Reviewer account

Use the demo agency's **owner** login, so no screen is hidden from the reviewer.

1. On the API server run \`npm run seed:showcase\` (see the API repo's \`scripts/seedShowcase.mjs\`). It creates the demo agency with sample data.
2. Type that owner email and password straight into the Play Console **App access** form. Never write them into this file: the repo may become public.
3. Before submitting, sign in with them at the live app in a private window.

---

## 6. Production release

| Field | Paste |
|---|---|
| Release name | \`1.0.0\` |
| Countries | India |
| Rollout | **20%** staged |

**Release notes** (max 500 — this is ${n4})

${code(notes)}

The \`.aab\` comes from GitHub → Actions → **Build Android (.aab)** → profile **production**. Download it from the repo's **Releases** page.

---

## 7. Before you press submit

- [ ] **Subscription payments inside the Android app.** The Plan screen has a "Pay now" button that opens Razorpay. Google Play requires Play Billing for subscriptions bought inside an app, and can reject or remove an app that takes payment another way. Decide before submitting: hide the pay buttons in the Android build (agencies pay on the web), or join Google's alternative-billing programme for India.
- [ ] Reviewer login created on the live server and tested in a private window
- [ ] Both URLs in §0 open the right page
- [ ] \`.aab\` built from the **production** profile, not preview
- [ ] The first production build's signing key is stored on Expo (account \`bharat-rail-gos-team\`). Do not delete that Expo project: Play accepts updates only from the same key.
- [ ] A trademark search for "BharatRailGo" is done
- [ ] New personal developer accounts must run a closed test with 12 testers for 14 days before production access. Organisation accounts are exempt.
`;

writeFileSync(path.join(FRONT, "docs", "playstore-listing.md"), md);
console.log(`docs/playstore-listing.md — name ${n1}/30, short ${n2}/80, full ${n3}/4000, notes ${n4}/500`);
